Makes ManyEnvelope sticky
icarus-consulting/Yaapii.Atoms pull request #426
Opened 2020-09-08 11:35 UTC by MSE1188

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior?
closes #425 

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications

###  Other information

2020-09-08 12:07 UTC, aveXcaesar approved these changes

2020-09-14 12:19 UTC, Meerownymous requested changes
With the proposed change, we always copy complete lists. We should instead use an approach where we only copy items if we also want to use them, meaning only copy when we move the enumerator.

This may be solved using a StickyFunc and an index.

2020-09-15 08:00 UTC, Meerownymous commented
PR closed due to other solution realized in #430

2020-09-15 08:00 UTC, closed without merging

2020-09-17 07:16 UTC, aveXcaesar commented on src/Yaapii.Atoms/Enumerable/Cycled.cs
> +                new ScalarOf<IEnumerator<T>>(() =>
I got it.
Unfortunately a test is missing to cover this.