Fix Union ctor to make compare function usable
icarus-consulting/Yaapii.Atoms pull request #429
Opened 2020-09-09 14:32 UTC by aveXcaesar

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

closes #427 

### What is the new behavior?

Union with compare function: `Union(IEnumerable<T> a, IEnumerable<T> b, Func<T, T, bool> compare)`

### Does this PR introduce a breaking change? (check one with "x")
- [x] Yes
- [ ] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications
Change ctor from
`Union(IEnumerable<T> a, IEnumerable<T> b, Func<T, bool> compare)`
to
`Union(IEnumerable<T> a, IEnumerable<T> b, Func<T, T, bool> compare)`
###  Other information
I can't imagine any use case for the refactored ctor `Union(IEnumerable<T> a, IEnumerable<T> b, Func<T, bool> compare)`.
If there is any I can undo deleting this and thus remove the breaking change.
What do you think?

2020-09-14 16:20 UTC, Meerownymous requested changes

2020-09-14 16:20 UTC, Meerownymous commented on src/Yaapii.Atoms/Enumerable/Union.cs
> +        /// <param name="compare">Decission to put items from a in the resulting union</param>
```suggestion
        /// <param name="compare">Condition for to match</param>
```

2020-09-14 16:20 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/Enumerable/UnionTests.cs
> +            var expected = new ListOf<string>("c:/abraham/a.jpg", "c:/caesar/c.jpg");
plz put this into line 78 as this is unnecessary temporal coupling.

2020-09-14 16:20 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/Enumerable/UnionTests.cs
> +            var a = new ListOf<string>("c:/abraham/a.jpg", "c:/bertram/b.jpg", "c:/caesar/c.jpg");
plz put this into line 80 as this is unnecessary temporal coupling.

2020-09-14 16:20 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/Enumerable/UnionTests.cs
> +            var b = new ListOf<string>("a", "c");
plz put this into line 81 as this is unnecessary temporal coupling.

2020-09-14 16:20 UTC, Meerownymous commented on src/Yaapii.Atoms/Enumerable/Union.cs
> +
plz remove

2020-09-23 09:50 UTC, aveXcaesar commented
@Meerownymous 
It's done

2020-10-19 12:27 UTC, aveXcaesar commented
@koeeenig 
please have a look and merge the pr if possible.

2020-10-26 11:32 UTC, koeeenig approved these changes

2020-11-02 10:44 UTC, aveXcaesar commented
@koeeenig @Meerownymous 
please merge...

2020-11-04 08:25 UTC, merged