fix: add test for WriterAsOutoutStream
icarus-consulting/Yaapii.Atoms pull request #506
Opened 2022-03-29 08:51 UTC by LeonardKrml

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)
#489 

### What is the new behavior?
added tests

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications

###  Other information

2022-03-29 15:13 UTC, icaOBU approved these changes

2022-04-04 13:03 UTC, Meerownymous requested changes

2022-04-04 13:03 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/IO/WriterAsOutputStreamTest.cs
> +            Directory.CreateDirectory(dir);
This leaves the directory present after the test. We always want to cleanup after a test (and be sure that we do not test data from a previous test). Please have a look at the object TempDirectory and TempFile and use them here.

2022-04-04 13:03 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/IO/WriterAsOutputStreamTest.cs
> +            Assert.True(left == right, "input and output are not the same size");
Put the objects left and right directly into the Assert:
`Assert.True(new LengthOf(...).Value() == new LenghtOf(...).Value(), ...)`

2022-04-04 13:03 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/IO/WriterAsOutputStreamTest.cs
> +        public void TryRead()
Variable name must be a fact about the tested object. This is a fact what the test method does. Please rename to "RejectsReading".

2022-04-04 13:03 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/IO/WriterAsOutputStreamTest.cs
> +            Assert.ThrowsAny<NotImplementedException>(
Rename to RejectsSeeking

2022-04-04 13:03 UTC, Meerownymous commented on tests/Yaapii.Atoms.Tests/IO/WriterAsOutputStreamTest.cs
> +            var stream = new WriterAsOutputStream(
Do not declare a variable.

2022-04-07 08:24 UTC, Meerownymous approved these changes

2022-04-07 08:24 UTC, merged