fix: add test for SubText, rename parameter
icarus-consulting/Yaapii.Atoms pull request #507
Opened 2022-03-29 09:50 UTC by LeonardKrml

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)
#465 

### What is the new behavior?
renamed parameter ent to len, added test for SubText

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications

###  Other information

2022-03-29 12:39 UTC, icaOBU requested changes

2022-03-29 12:39 UTC, icaOBU commented on src/Yaapii.Atoms/Text/SubText.cs
> +        public SubText(String text, int strt, int len) : this(
Please adjust the parameter names so we can see for what the parameter is used. So you can remove the parameter description from header. Most programmers forget to adjust these comments and the parametrer name should say what the param stands for. 

Also please don't use abbreviations. I think this is old code and we should avoid something like that

2022-03-29 15:13 UTC, icaOBU approved these changes

2022-03-30 14:36 UTC, aveXcaesar requested changes
Only styling ;-)

2022-03-30 14:36 UTC, aveXcaesar commented on tests/Yaapii.Atoms.Tests/Text/SubTextTest.cs
> +                    8,3
```suggestion
                    8,
                    3
```

2022-03-30 14:36 UTC, aveXcaesar commented on tests/Yaapii.Atoms.Tests/Text/SubTextTest.cs
> +                    8, 3
```suggestion
                    8,
                    3
```

2022-04-01 14:05 UTC, aveXcaesar approved these changes

2022-04-04 11:15 UTC, jaanpeeter approved these changes

2022-04-04 12:57 UTC, merged