feat: add forkfunc
icarus-consulting/Yaapii.Atoms pull request #529
Opened 2023-01-27 07:54 UTC by jaanpeeter

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

#528 
### What is the new behavior?

closes #528 
### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications

###  Other information

2023-01-30 07:44 UTC, koeeenig commented
This behaviour might be better implemented with the interface proposed in #476 
AS mentioned in the issue, `Func` leads to procedural thinking. What do you think @MSE1188 @jaanpeeter  ?

2023-01-30 16:32 UTC, MSE1188 commented
Agree. ```ForkFunc``` is not a good name. ```Swap``` is better

2023-02-01 07:13 UTC, koeeenig commented
I would add the `ISwap` interface and keep the `IFunc` interface as well. In my opinion it fits into the library because using `ISwap`  or `IFunc` depends on the usecase.

2023-03-10 16:22 UTC, Meerownymous commented
From my perspective, func is something where I as the developer am the actor who triggers something that should happen with an input. It puts me in control and takes responsibility from the object. 

Swap can be seen as a permanent conversion, offering its services whenever needed.
I use it when I need a performant object which is seldomly constructed and does a lot of conversions during its lifetime. Because Atoms objects are all caching their result by default, the developer cannot use a chain of decorators for this - and making the these live comes at the cost of performance. 

To me swaps are handy to build a conversion object which is constructed as an app singleton.

Func and Swap are indeed identical and it is all about what story the developer intends their code to tell to future readers.

2023-03-16 08:06 UTC, koeeenig requested changes

2023-03-16 08:06 UTC, koeeenig commented on src/Yaapii.Atoms/Swap/SwapSwitch.cs
> +    public sealed class Tooth<TInput, TOutcome> : KvpEnvelope<TInput, Func<TOutcome>>
I suggest to rename `Tooth` to `SwapIf `..it's easier to understand.
Move the class to it's own file.

2023-03-16 08:06 UTC, koeeenig commented on src/Yaapii.Atoms/Swap/SwapSwitch.cs
We had an implementation in the [PAQO](https://github.com/icarus-consulting/PAQO/blob/main/src/PAQO.Core/Facets/SwapSwitch.cs) library for `SwapSwitch` as well. Would you mind moving the ctors from there into this implementation?

2023-03-16 10:03 UTC, koeeenig commented on src/Yaapii.Atoms/Swap/SwapSwitch.cs
`SwapSwitch<TInput, TOutput> : ISwap<string, TInput, TOutput>` tights the switch condition to be based on a string which is in most cases sufficient. However someone might need another type as condition so i would suggest `SwapSwitch<TCondition, TInput, TOutput> : ISwap<TCondition, TInput, TOutput>`.

You can additionaly add a `SwapSwitch` which sets the TCondition to string as in `SwapSwitch<TInput, TOutput> : ISwap<string, TInput, TOutput>`.

2023-03-17 09:18 UTC, MSE1188 approved these changes

2023-03-17 09:20 UTC, MSE1188 commented
ISwap now replaces the IFunc interface. We should also remove IFunc and the FuncOf class to prevent redundancy or at least add ```Obsolete``` attributes to these classes

2023-03-19 10:05 UTC, Meerownymous commented
I would not see Ifunc obsolete, as ISwap is a different thing: Where I expect IFunc to have effects beyond making an output when invoking, I would not expect ISawp to to anything else than give me the desired output. Hence it matters what the code is supposed to express.

I also think the original cactoos introduced it to allow for adopting non-interface library object "func" to interface and therefore allow the common eo patterns to be applied to it. The same like INumber or IText, which transform the primitives string and int/double etc to eo "types" (interfaces).

2023-03-20 09:37 UTC, koeeenig commented
i agree with @Meerownymous , `IFunc` enables the EO principle to inject `Func` into a constructor. We should definitely keep that in the library.

2023-03-20 09:39 UTC, koeeenig approved these changes

2023-06-26 07:47 UTC, merged